name: QiitaChecker
targets:
  QiitaChecker:
    type: application
    platform: iOS
    sources: 
      - QiitaChecker
    settings:
      base:
        MARKETING_VERSIONS: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: Kaoru Muta
        INFOPLIST_FILE: QiitaChecker/Common/Resource/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.muta.QiitaChecker
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: Alamofire
      - carthage: Parchment
      - carthage: Nuke
    preBuildScripts:
      - script: |
          Pods/SwiftLint/swiftlint autocorrect
        name: SwiftLint AutoCorrect
      - script: |
          Pods/SwiftLint/swiftlint
        name: SwiftLint
  QiitaCheckerTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: QiitaCheckerTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.muta.QiitaCheckerTests
    dependencies: 
      - target: QiitaChecker
  QiitaCheckerUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: QiitaCheckerUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.muta.QiitaCheckerUITests
    dependencies: 
      - target: QiitaChecker
    