name: QiitaChecker
targets:
  QiitaChecker:
    type: application
    platform: iOS
    sources: 
      - QiitaChecker
    settings:
      base:
        MARKETING_VERSIONS: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: Kaoru Muta
        INFOPLIST_FILE: QiitaChecker/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.muta.QiitaChecker
    dependencies:
      - carthage: RxSwift
        linktype: static
      - carthage: RxCocoa
        linktype: static
      - carthage: RxRelay
        linktype: static
      - carthage: Alamofire
    postbuildScripts:
      - script: ${SRCROOT}/Pods/SwiftLint/swiftlint autocorrect\n${PODS_ROOT}/SwiftLint/swiftlint lint
        name: Swiftlint Run Script
  QiitaCheckerTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: QiitaCheckerTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.muta.QiitaCheckerTests
  QiitaCheckerUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: QiitaCheckerUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.muta.QiitaCheckerUITests
    